name: Update package repositories

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    strategy:
      matrix:
        platform:
          - ubuntu-22.04
          - macos-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Update package repositories
        env:
          LIMIT: 100
          PLATFORM: ${{ matrix.platform }}
        run: Rscript inst/scripts/github_action.R
      - name: Save changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add .
          git diff-index --quiet HEAD || git commit -m "Update package repositories"
          git push
